export const MARKET_ACTIONS = {
  CHECK_CART_ITEMS: 'CHECK_CART_ITEMS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  GET_CART_ITEMS: 'GET_CART_ITEMS',
  GET_CATALOG_ITEMS: 'GET_CATALOG_ITEMS',
  VIEW_PRODUCT: 'VIEW_PRODUCT',
  CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
  ADD_TO_DB: 'ADD_TO_DB',
}